Add hooks in for running in a fake crossbuild case, i.e. build under cygwin but using mingw compilers targetting mingw.  This is because my recent cygwin install has removed the -mno-cygwin option to gcc.  While here also make this script a bit more portable to work unchanged with both pcb and gerbv so I hopefully don't have to work as much to maintain both.

diff --git a/win32/build_gerbv b/win32/build_gerbv
--- a/win32/build_gerbv
+++ b/win32/build_gerbv
@@ -1,6 +1,5 @@
 #!/bin/sh
 #
-# $Id$
 #
 
 # error out on failed commands whose return code wasn't explicitly
@@ -12,7 +11,7 @@ cat << EOF
 
 $0 [options]
 
-Builds a non-cygwin version of gerbv and create a standalone
+Builds a non-cygwin version of gerbv or pcb and create a standalone
 windows installer.
 
 Supported options:
@@ -28,7 +27,7 @@ Supported options:
                     down to the configure script which enables 
                     a good bit of debug output.
 
-  --help          - Show this message and exit.
+  -h|--help       - Show this message and exit.
 
   --force-autogen - Force running ./autogen.sh.  Normally this is
                     only done if the configure script is not present.
@@ -51,6 +50,17 @@ as well as gdlib installed on your system in very specific
 locations.  Edit $0 to change these.  While you are at it, feel
 free to provide a patch to improve the documentation about 
 those libraries.
+
+On older installs of cygwin, the available gcc will accept -mno-cygwin
+to build an executible that does not link to the cygwin dll.  On newer
+gcc's this option has been removed and you must use either a
+cross compiler that targets mingw or use the native MinGW compiler.
+If you use the native MinGW compiler approach, then 
+the MinGW compilers to be installed in
+c:\MinGW and also in your cygwin environment there needs to be
+a symbolic link:
+
+/mingw -> /cygdrive/c/MinGW
 
 EOF
 }
@@ -81,7 +91,7 @@ while test $# -ne 0 ; do
 			shift
 			;;
 
-		--help)
+		-h|--help)
 			usage
 			exit 0
 			;;
@@ -136,12 +146,30 @@ while test $# -ne 0 ; do
 	esac
 done
 
-if test ! -f win32/build_gerbv ; then
-	echo "$0:  ERROR.  This script must be run from the top level of the gerbv source tree."
+prog_name=unknown
+if test ! -d win32 ; then
+	echo "$0:  ERROR.  This script must be run from the top level of the source tree"
 	exit 1
 fi
 
-# Run this under cygwin to build gerbv and create a windows installer for
+if test -f src/gerbv.c ; then
+	prog_name=gerbv
+fi
+
+if test -f src/pcb-menu.res ; then
+	prog_name=pcb
+fi
+
+if test ${prog_name} = unknown ; then
+	cat << EOF
+$0:  ERROR.  Unable to figure out what you are building.
+This may happen if you are trying to execute $0 from a directory
+other than the top of the source tree.
+EOF
+	exit 1
+fi
+
+# Run this under cygwin to build gerbv or pcb and create a windows installer for
 # it.  Thanks to Bob Paddock for pointing me to NSIS and answering some 
 # beginner windows questions.
 
@@ -151,10 +179,10 @@ gtk_win32=c:\\cygwin\\home\\${USER}\\gtk_win32
 # where only the runtime components are installed
 gtk_win32_runtime=c:\\\\cygwin\\\\home\\\\${USER}\\\\gtk_win32_runtime
 
-# gerbv version
+# program version
 
-gerbv_version=`awk '/AC_INIT/ {gsub(/.*,[ \t]*\[/, ""); gsub(/\]\).*/, ""); print}' configure.ac`
-echo "gerbv_version=${gerbv_version}"
+prog_version=`awk '/AC_INIT/ {gsub(/.*,[ \t]*\[/, ""); gsub(/\]\).*/, ""); print}' configure.ac`
+echo "prog_version=${prog_version}"
 
 # location of the NSIS makensis executible (see http://nsis.sourceforge.net)
 makensis="/cygdrive/c/Program Files/NSIS/makensis.exe"
@@ -180,11 +208,11 @@ src_dir=c:\\\\cygwin`echo ${srcdir} | sed 's;/;\\\\\\\\;g'`
 top_src_dir=c:\\\\cygwin`echo ${top_srcdir} | sed 's;/;\\\\\\\\;g'`
 
 
-# where to install gerbv
-gerbv_inst=`pwd`/gerbv_inst
+# where to install the program
+prog_inst=`pwd`/${prog_name}_inst
 
 # DOS version
-gerbv_inst_dir=c:\\\\cygwin`echo ${gerbv_inst} | sed 's;/;\\\\\\\\;g'`
+prog_inst_dir=c:\\\\cygwin`echo ${prog_inst} | sed 's;/;\\\\\\\\;g'`
 
 PKG_CONFIG_PATH=${gtk_win32}\\lib\\pkgconfig
 export PKG_CONFIG_PATH
@@ -197,11 +225,17 @@ pkg-config --list-all
 
 
 # do not try to use libpng-config, it seems broken on win32
+if test $prog_name = pcb ; then
+	LIBPNG_CFLAGS="-I${HOME}/gtk_win32/include"
+	LIBPNG_LDFLAGS="-L${HOME}/gtk_win32/lib"
+	LIBPNG_LIBS="-lpng12"
+else
+	LIBPNG_CFLAGS=""
+	LIBPNG_LDFLAGS=""
+	LIBPNG_LIBS=""
+fi
 LIBPNG_CONFIG=/usr/bin/true
 export LIBPNG_CONFIG
-LIBPNG_CFLAGS="-I${HOME}/gtk_win32/include"
-LIBPNG_LDFLAGS="-L${HOME}/gtk_win32/lib"
-LIBPNG_LIBS="-lpng12"
 
 # add the gcc options to produce a native windows binary that
 # does not need cygwin to run
@@ -215,6 +249,39 @@ export CYGWIN_CFLAGS
 CYGWIN_CPPFLAGS="-mms-bitfields -mno-cygwin ${EXTRA_FLAGS}"
 export CYGWIN_CPPFLAGS
 
+
+do_fake_crossbuild=no
+if test -f /mingw/bin/mingw32-gcc.exe ; then
+	do_fake_crossbuild=yes
+fi
+
+echo "do_fake_crossbuild = ${do_fake_crossbuild}"
+
+# older releases of cygwin had a gcc that accepted -mno-cygwin.
+# in more recent releases this flag (which builds and links without
+# the cygwin dll) has been removed.  We either need a normal
+# cross compiler or we can fake it by using the native mingw
+# compiler.  
+# see http://www.gnu.org/software/libtool/manual/html_node/Cygwin-to-MinGW-Cross.html
+# in particular, the lt_cv_to_tool_file_cmd bit is needed because
+# libtool will call the mingw ranlib which will not understand
+# any cygwin absolute paths.  
+if test ${do_fake_crossbuild} = yes ; then
+	config_args="${config_args} --build=i686-pc-cygwin --host=mingw32"
+	NM=/cygdrive/c/MinGW/bin/nm.exe
+	export NM
+
+	# the ranlib bit here is because putting the mingw tools first
+	# in PATH causes the mingw ranlib to be called.  The problem
+	# with that is tht libtool is passing an absolute cygwin
+	# path at install time to ranlib which can't deal.  The
+	# func_convert... stuff is supposed to help but it didn't
+	RANLIB=/usr/bin/ranlib
+	export RANLIB
+	PATH=/cygdrive/c/MinGW/bin:${PATH}
+	export lt_cv_to_tool_file_cmd=func_convert_file_cygwin_to_w32
+fi
+
 # setting WIN32=yes will make sure that the desktop icon
 # gets compiled in
 if test "$do_config" = "yes" ; then
@@ -222,7 +289,7 @@ rm -fr src/.deps
 echo "Configuring for cygwin"
 ( ( ( env WIN32=yes \
 	./configure \
-	--prefix=${gerbv_inst} \
+	--prefix=${prog_inst} \
 	--disable-dependency-tracking \
 	--disable-maintainer-mode \
 	--disable-nls \
@@ -281,8 +348,8 @@ if test "$do_install" = "yes" ; then
 echo "Installing for cygwin"
 # first clean out the installation directory to make sure
 # we don't have old junk lying around.
-if test -d ${gerbv_inst} ; then
-	rm -fr ${gerbv_inst}
+if test -d ${prog_inst} ; then
+	rm -fr ${prog_inst}
 fi
 ( ( ( make install 2>&1 ; echo $? >&4) | tee -a m.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
 if test $? -ne 0 ; then
@@ -299,14 +366,14 @@ echo "top_srcdir = ${top_srcdir}"
 echo "top_src_dir = ${top_src_dir}"
 
 sed \
-	-e "s;@gerbv_version@;${gerbv_version};g" \
-	-e "s;@gerbv_prefix@;${gerbv_inst_dir};g" \
-	-e "s;@gerbv_srcdir@;${top_src_dir};g" \
+	-e "s;@prog_version@;${prog_version};g" \
+	-e "s;@prog_prefix@;${prog_inst_dir};g" \
+	-e "s;@prog_srcdir@;${top_src_dir};g" \
 	-e "s;@gtk_win32_runtime@;${gtk_win32_runtime};g" \
-	${srcdir}/gerbv.nsi.in > ${srcdir}/gerbv.nsi
+	${srcdir}/${prog_name}.nsi.in > ${srcdir}/${prog_name}.nsi
 
 echo "Creating windows installer"
-"${makensis}" ${src_dir}/gerbv.nsi
+"${makensis}" ${src_dir}/${prog_name}.nsi
 
 
 echo "Windows installer left in ${srcdir}:"
@@ -329,7 +396,7 @@ EOF
 
 cat > ${bat} << EOF
 
-.\win32\gerbvinst-${gerbv_version}.exe
+.\win32\\${prog_name}inst-${prog_version}.exe
 
 EOF
 chmod 755 ${bat}
